name: Build + deploy

on:
  workflow_call:
    inputs:
      registry:
        description: The OCI registry to push to
        required: true
        type: string
      repository:
        description: The which repository to push to within the OCI registry
        required: true
        type: string
    secrets:
      registry-user:
        description: The OCI registry user
        required: true
      registry-password:
        description: The OCI registry user's password
        required: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.registry-user }}
          password: ${{ secrets.registry-password }}
      - name: Build image
        run: >-
          docker build
          -t ${{ inputs.registry }}/${{ inputs.repository }}:latest
          -t ${{ inputs.registry }}/${{ inputs.repository }}:$(date +%s)
          --cache-from ${{ inputs.registry }}/${{ inputs.repository }}:latest
          --build-arg BUILDKIT_INLINE_CACHE=1
          .
        env:
          DOCKER_BUILDKIT: "1"
      - name: Push image
        run: docker push --all-tags ${{ inputs.registry }}/${{ inputs.repository }}
