name: Build + deploy

on:
  workflow_call:
    inputs:
      registry:
        description: The OCI registry to push to
        required: true
        type: string
      repository:
        description: The which repository to push to within the OCI registry
        required: true
        type: string
    secrets:
      registry-user:
        description: The OCI registry user
        required: true
      registry-password:
        description: The OCI registry user's password
        required: true

env:
  DOCKER_BUILDKIT: "1"
  IMAGE_BASE: ${{ inputs.registry }}/${{ inputs.repository }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.registry-user }}
          password: ${{ secrets.registry-password }}
      - name: Compute version tag
        id: compute_tag
        run: echo "tag=$(date +%s)" >> "$GITHUB_OUTPUT"
      - name: Build image (${{ steps.compute_tag.outputs.tag }})
        run: >-
          docker build
          -t ${{ env.IMAGE_BASE }}:latest
          -t ${{ env.IMAGE_BASE }}:${{ steps.compute_tag.outputs.tag }}
          --cache-from ${{ env.IMAGE_BASE }}:latest
          --build-arg BUILDKIT_INLINE_CACHE=1
          .
      - name: Push image
        run: docker push --all-tags ${{ env.IMAGE_BASE }}
      - name: Output summary
        run: echo '${{ env.IMAGE_BASE }}:${{ steps.compute_tag.outputs.tag }}' >> $GITHUB_STEP_SUMMARY
